// GENERATED by tools/desktop/gen-wl-protocol.py - do not edit.
// Sources:
//   wayland.xml  sha256 cc860987e54f8d85c940e97fa1270c69b6e4ad31fbcf5a7f00107ce1157f5e07
//   xdg-shell.xml  sha256 7ba7f9c8473deee674cb1f154a18abd0bb0cc072604fc055b0c15e459fc4c7df
//   xdg-decoration-unstable-v1.xml  sha256 68753c4a85a28659e3aa1fe0f138329a8bf3dff0b4789f4663a2c7fedbfecf2f
//   viewporter.xml  sha256 dcb12279a03746301fe490aaed4b38a403485a925abfce2ccfceb644e104fe71
//
// Each message's arguments in wire order, and how many are descriptors. A
// new_id with no interface is wl_registry.bind's, which the client names.

use super::protocol::{Arg, Interface, Message};

pub static INTERFACES: &[Interface] = &[
    Interface {
        name: "wl_display",
        version: 1,
        requests: &[
            Message { name: "sync", args: &[Arg::NewId { iface: Some("wl_callback") }], fds: 0, since: 1 },
            Message { name: "get_registry", args: &[Arg::NewId { iface: Some("wl_registry") }], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "error", args: &[Arg::Object { nullable: false }, Arg::Uint, Arg::String { nullable: false }], fds: 0, since: 1 },
            Message { name: "delete_id", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_registry",
        version: 1,
        requests: &[
            Message { name: "bind", args: &[Arg::Uint, Arg::NewId { iface: None }], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "global", args: &[Arg::Uint, Arg::String { nullable: false }, Arg::Uint], fds: 0, since: 1 },
            Message { name: "global_remove", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_callback",
        version: 1,
        requests: &[
        ],
        events: &[
            Message { name: "done", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_compositor",
        version: 7,
        requests: &[
            Message { name: "create_surface", args: &[Arg::NewId { iface: Some("wl_surface") }], fds: 0, since: 1 },
            Message { name: "create_region", args: &[Arg::NewId { iface: Some("wl_region") }], fds: 0, since: 1 },
            Message { name: "release", args: &[], fds: 0, since: 7 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shm_pool",
        version: 3,
        requests: &[
            Message { name: "create_buffer", args: &[Arg::NewId { iface: Some("wl_buffer") }, Arg::Int, Arg::Int, Arg::Int, Arg::Int, Arg::Uint], fds: 0, since: 1 },
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "resize", args: &[Arg::Int], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shm",
        version: 3,
        requests: &[
            Message { name: "create_pool", args: &[Arg::NewId { iface: Some("wl_shm_pool") }, Arg::Fd, Arg::Int], fds: 1, since: 1 },
            Message { name: "release", args: &[], fds: 0, since: 2 },
        ],
        events: &[
            Message { name: "format", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_buffer",
        version: 1,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "release", args: &[], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_data_offer",
        version: 4,
        requests: &[
            Message { name: "accept", args: &[Arg::Uint, Arg::String { nullable: true }], fds: 0, since: 1 },
            Message { name: "receive", args: &[Arg::String { nullable: false }, Arg::Fd], fds: 1, since: 1 },
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "finish", args: &[], fds: 0, since: 3 },
            Message { name: "set_actions", args: &[Arg::Uint, Arg::Uint], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "offer", args: &[Arg::String { nullable: false }], fds: 0, since: 1 },
            Message { name: "source_actions", args: &[Arg::Uint], fds: 0, since: 3 },
            Message { name: "action", args: &[Arg::Uint], fds: 0, since: 3 },
        ],
    },
    Interface {
        name: "wl_data_source",
        version: 4,
        requests: &[
            Message { name: "offer", args: &[Arg::String { nullable: false }], fds: 0, since: 1 },
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "set_actions", args: &[Arg::Uint], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "target", args: &[Arg::String { nullable: true }], fds: 0, since: 1 },
            Message { name: "send", args: &[Arg::String { nullable: false }, Arg::Fd], fds: 1, since: 1 },
            Message { name: "cancelled", args: &[], fds: 0, since: 1 },
            Message { name: "dnd_drop_performed", args: &[], fds: 0, since: 3 },
            Message { name: "dnd_finished", args: &[], fds: 0, since: 3 },
            Message { name: "action", args: &[Arg::Uint], fds: 0, since: 3 },
        ],
    },
    Interface {
        name: "wl_data_device",
        version: 4,
        requests: &[
            Message { name: "start_drag", args: &[Arg::Object { nullable: true }, Arg::Object { nullable: false }, Arg::Object { nullable: true }, Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_selection", args: &[Arg::Object { nullable: true }, Arg::Uint], fds: 0, since: 1 },
            Message { name: "release", args: &[], fds: 0, since: 2 },
        ],
        events: &[
            Message { name: "data_offer", args: &[Arg::NewId { iface: Some("wl_data_offer") }], fds: 0, since: 1 },
            Message { name: "enter", args: &[Arg::Uint, Arg::Object { nullable: false }, Arg::Fixed, Arg::Fixed, Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "leave", args: &[], fds: 0, since: 1 },
            Message { name: "motion", args: &[Arg::Uint, Arg::Fixed, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "drop", args: &[], fds: 0, since: 1 },
            Message { name: "selection", args: &[Arg::Object { nullable: true }], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_data_device_manager",
        version: 4,
        requests: &[
            Message { name: "create_data_source", args: &[Arg::NewId { iface: Some("wl_data_source") }], fds: 0, since: 1 },
            Message { name: "get_data_device", args: &[Arg::NewId { iface: Some("wl_data_device") }, Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "release", args: &[], fds: 0, since: 4 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shell",
        version: 1,
        requests: &[
            Message { name: "get_shell_surface", args: &[Arg::NewId { iface: Some("wl_shell_surface") }, Arg::Object { nullable: false }], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shell_surface",
        version: 1,
        requests: &[
            Message { name: "pong", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "move", args: &[Arg::Object { nullable: false }, Arg::Uint], fds: 0, since: 1 },
            Message { name: "resize", args: &[Arg::Object { nullable: false }, Arg::Uint, Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_toplevel", args: &[], fds: 0, since: 1 },
            Message { name: "set_transient", args: &[Arg::Object { nullable: false }, Arg::Int, Arg::Int, Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_fullscreen", args: &[Arg::Uint, Arg::Uint, Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "set_popup", args: &[Arg::Object { nullable: false }, Arg::Uint, Arg::Object { nullable: false }, Arg::Int, Arg::Int, Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_maximized", args: &[Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "set_title", args: &[Arg::String { nullable: false }], fds: 0, since: 1 },
            Message { name: "set_class", args: &[Arg::String { nullable: false }], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "ping", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "configure", args: &[Arg::Uint, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "popup_done", args: &[], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wl_surface",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "attach", args: &[Arg::Object { nullable: true }, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "damage", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "frame", args: &[Arg::NewId { iface: Some("wl_callback") }], fds: 0, since: 1 },
            Message { name: "set_opaque_region", args: &[Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "set_input_region", args: &[Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "commit", args: &[], fds: 0, since: 1 },
            Message { name: "set_buffer_transform", args: &[Arg::Int], fds: 0, since: 2 },
            Message { name: "set_buffer_scale", args: &[Arg::Int], fds: 0, since: 3 },
            Message { name: "damage_buffer", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 4 },
            Message { name: "offset", args: &[Arg::Int, Arg::Int], fds: 0, since: 5 },
            Message { name: "get_release", args: &[Arg::NewId { iface: Some("wl_callback") }], fds: 0, since: 7 },
        ],
        events: &[
            Message { name: "enter", args: &[Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "leave", args: &[Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "preferred_buffer_scale", args: &[Arg::Int], fds: 0, since: 6 },
            Message { name: "preferred_buffer_transform", args: &[Arg::Uint], fds: 0, since: 6 },
        ],
    },
    Interface {
        name: "wl_seat",
        version: 11,
        requests: &[
            Message { name: "get_pointer", args: &[Arg::NewId { iface: Some("wl_pointer") }], fds: 0, since: 1 },
            Message { name: "get_keyboard", args: &[Arg::NewId { iface: Some("wl_keyboard") }], fds: 0, since: 1 },
            Message { name: "get_touch", args: &[Arg::NewId { iface: Some("wl_touch") }], fds: 0, since: 1 },
            Message { name: "release", args: &[], fds: 0, since: 5 },
        ],
        events: &[
            Message { name: "capabilities", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "name", args: &[Arg::String { nullable: false }], fds: 0, since: 2 },
        ],
    },
    Interface {
        name: "wl_pointer",
        version: 11,
        requests: &[
            Message { name: "set_cursor", args: &[Arg::Uint, Arg::Object { nullable: true }, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "release", args: &[], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "enter", args: &[Arg::Uint, Arg::Object { nullable: false }, Arg::Fixed, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "leave", args: &[Arg::Uint, Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "motion", args: &[Arg::Uint, Arg::Fixed, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "button", args: &[Arg::Uint, Arg::Uint, Arg::Uint, Arg::Uint], fds: 0, since: 1 },
            Message { name: "axis", args: &[Arg::Uint, Arg::Uint, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "frame", args: &[], fds: 0, since: 5 },
            Message { name: "axis_source", args: &[Arg::Uint], fds: 0, since: 5 },
            Message { name: "axis_stop", args: &[Arg::Uint, Arg::Uint], fds: 0, since: 5 },
            Message { name: "axis_discrete", args: &[Arg::Uint, Arg::Int], fds: 0, since: 5 },
            Message { name: "axis_value120", args: &[Arg::Uint, Arg::Int], fds: 0, since: 8 },
            Message { name: "axis_relative_direction", args: &[Arg::Uint, Arg::Uint], fds: 0, since: 9 },
            Message { name: "warp", args: &[Arg::Fixed, Arg::Fixed], fds: 0, since: 11 },
        ],
    },
    Interface {
        name: "wl_keyboard",
        version: 11,
        requests: &[
            Message { name: "release", args: &[], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "keymap", args: &[Arg::Uint, Arg::Fd, Arg::Uint], fds: 1, since: 1 },
            Message { name: "enter", args: &[Arg::Uint, Arg::Object { nullable: false }, Arg::Array], fds: 0, since: 1 },
            Message { name: "leave", args: &[Arg::Uint, Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "key", args: &[Arg::Uint, Arg::Uint, Arg::Uint, Arg::Uint], fds: 0, since: 1 },
            Message { name: "modifiers", args: &[Arg::Uint, Arg::Uint, Arg::Uint, Arg::Uint, Arg::Uint], fds: 0, since: 1 },
            Message { name: "repeat_info", args: &[Arg::Int, Arg::Int], fds: 0, since: 4 },
        ],
    },
    Interface {
        name: "wl_touch",
        version: 11,
        requests: &[
            Message { name: "release", args: &[], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "down", args: &[Arg::Uint, Arg::Uint, Arg::Object { nullable: false }, Arg::Int, Arg::Fixed, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "up", args: &[Arg::Uint, Arg::Uint, Arg::Int], fds: 0, since: 1 },
            Message { name: "motion", args: &[Arg::Uint, Arg::Int, Arg::Fixed, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "frame", args: &[], fds: 0, since: 1 },
            Message { name: "cancel", args: &[], fds: 0, since: 1 },
            Message { name: "shape", args: &[Arg::Int, Arg::Fixed, Arg::Fixed], fds: 0, since: 6 },
            Message { name: "orientation", args: &[Arg::Int, Arg::Fixed], fds: 0, since: 6 },
        ],
    },
    Interface {
        name: "wl_output",
        version: 4,
        requests: &[
            Message { name: "release", args: &[], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "geometry", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int, Arg::Int, Arg::String { nullable: false }, Arg::String { nullable: false }, Arg::Int], fds: 0, since: 1 },
            Message { name: "mode", args: &[Arg::Uint, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "done", args: &[], fds: 0, since: 2 },
            Message { name: "scale", args: &[Arg::Int], fds: 0, since: 2 },
            Message { name: "name", args: &[Arg::String { nullable: false }], fds: 0, since: 4 },
            Message { name: "description", args: &[Arg::String { nullable: false }], fds: 0, since: 4 },
        ],
    },
    Interface {
        name: "wl_region",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "add", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "subtract", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_subcompositor",
        version: 1,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "get_subsurface", args: &[Arg::NewId { iface: Some("wl_subsurface") }, Arg::Object { nullable: false }, Arg::Object { nullable: false }], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_subsurface",
        version: 1,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "set_position", args: &[Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "place_above", args: &[Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "place_below", args: &[Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "set_sync", args: &[], fds: 0, since: 1 },
            Message { name: "set_desync", args: &[], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_fixes",
        version: 2,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "destroy_registry", args: &[Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "ack_global_remove", args: &[Arg::Object { nullable: false }, Arg::Uint], fds: 0, since: 2 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "xdg_wm_base",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "create_positioner", args: &[Arg::NewId { iface: Some("xdg_positioner") }], fds: 0, since: 1 },
            Message { name: "get_xdg_surface", args: &[Arg::NewId { iface: Some("xdg_surface") }, Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "pong", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "ping", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "xdg_positioner",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "set_size", args: &[Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "set_anchor_rect", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "set_anchor", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_gravity", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_constraint_adjustment", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_offset", args: &[Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "set_reactive", args: &[], fds: 0, since: 3 },
            Message { name: "set_parent_size", args: &[Arg::Int, Arg::Int], fds: 0, since: 3 },
            Message { name: "set_parent_configure", args: &[Arg::Uint], fds: 0, since: 3 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "xdg_surface",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "get_toplevel", args: &[Arg::NewId { iface: Some("xdg_toplevel") }], fds: 0, since: 1 },
            Message { name: "get_popup", args: &[Arg::NewId { iface: Some("xdg_popup") }, Arg::Object { nullable: true }, Arg::Object { nullable: false }], fds: 0, since: 1 },
            Message { name: "set_window_geometry", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "ack_configure", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "configure", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "xdg_toplevel",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "set_parent", args: &[Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "set_title", args: &[Arg::String { nullable: false }], fds: 0, since: 1 },
            Message { name: "set_app_id", args: &[Arg::String { nullable: false }], fds: 0, since: 1 },
            Message { name: "show_window_menu", args: &[Arg::Object { nullable: false }, Arg::Uint, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "move", args: &[Arg::Object { nullable: false }, Arg::Uint], fds: 0, since: 1 },
            Message { name: "resize", args: &[Arg::Object { nullable: false }, Arg::Uint, Arg::Uint], fds: 0, since: 1 },
            Message { name: "set_max_size", args: &[Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "set_min_size", args: &[Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "set_maximized", args: &[], fds: 0, since: 1 },
            Message { name: "unset_maximized", args: &[], fds: 0, since: 1 },
            Message { name: "set_fullscreen", args: &[Arg::Object { nullable: true }], fds: 0, since: 1 },
            Message { name: "unset_fullscreen", args: &[], fds: 0, since: 1 },
            Message { name: "set_minimized", args: &[], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "configure", args: &[Arg::Int, Arg::Int, Arg::Array], fds: 0, since: 1 },
            Message { name: "close", args: &[], fds: 0, since: 1 },
            Message { name: "configure_bounds", args: &[Arg::Int, Arg::Int], fds: 0, since: 4 },
            Message { name: "wm_capabilities", args: &[Arg::Array], fds: 0, since: 5 },
        ],
    },
    Interface {
        name: "xdg_popup",
        version: 7,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "grab", args: &[Arg::Object { nullable: false }, Arg::Uint], fds: 0, since: 1 },
            Message { name: "reposition", args: &[Arg::Object { nullable: false }, Arg::Uint], fds: 0, since: 3 },
        ],
        events: &[
            Message { name: "configure", args: &[Arg::Int, Arg::Int, Arg::Int, Arg::Int], fds: 0, since: 1 },
            Message { name: "popup_done", args: &[], fds: 0, since: 1 },
            Message { name: "repositioned", args: &[Arg::Uint], fds: 0, since: 3 },
        ],
    },
    Interface {
        name: "zxdg_decoration_manager_v1",
        version: 2,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "get_toplevel_decoration", args: &[Arg::NewId { iface: Some("zxdg_toplevel_decoration_v1") }, Arg::Object { nullable: false }], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "zxdg_toplevel_decoration_v1",
        version: 2,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "set_mode", args: &[Arg::Uint], fds: 0, since: 1 },
            Message { name: "unset_mode", args: &[], fds: 0, since: 1 },
        ],
        events: &[
            Message { name: "configure", args: &[Arg::Uint], fds: 0, since: 1 },
        ],
    },
    Interface {
        name: "wp_viewporter",
        version: 1,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "get_viewport", args: &[Arg::NewId { iface: Some("wp_viewport") }, Arg::Object { nullable: false }], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wp_viewport",
        version: 1,
        requests: &[
            Message { name: "destroy", args: &[], fds: 0, since: 1 },
            Message { name: "set_source", args: &[Arg::Fixed, Arg::Fixed, Arg::Fixed, Arg::Fixed], fds: 0, since: 1 },
            Message { name: "set_destination", args: &[Arg::Int, Arg::Int], fds: 0, since: 1 },
        ],
        events: &[
        ],
    },
];
