// GENERATED by tools/desktop/gen-wl-protocol.py - do not edit.
// Sources:
//   wayland.xml  sha256 cc860987e54f8d85c940e97fa1270c69b6e4ad31fbcf5a7f00107ce1157f5e07
//   xdg-shell.xml  sha256 7ba7f9c8473deee674cb1f154a18abd0bb0cc072604fc055b0c15e459fc4c7df
//   xdg-decoration-unstable-v1.xml  sha256 68753c4a85a28659e3aa1fe0f138329a8bf3dff0b4789f4663a2c7fedbfecf2f
//   viewporter.xml  sha256 dcb12279a03746301fe490aaed4b38a403485a925abfce2ccfceb644e104fe71
//
// Signature letters: i u f s o n a h; '?' marks a nullable o/s; n:iface names
// the new object's interface, n:* means the client names it (wl_registry.bind).

use super::protocol::{Interface, Message};

pub static INTERFACES: &[Interface] = &[
    Interface {
        name: "wl_display",
        version: 1,
        requests: &[
            Message { name: "sync", sig: "n:wl_callback", since: 1 },
            Message { name: "get_registry", sig: "n:wl_registry", since: 1 },
        ],
        events: &[
            Message { name: "error", sig: "o u s", since: 1 },
            Message { name: "delete_id", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "wl_registry",
        version: 1,
        requests: &[
            Message { name: "bind", sig: "u n:*", since: 1 },
        ],
        events: &[
            Message { name: "global", sig: "u s u", since: 1 },
            Message { name: "global_remove", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "wl_callback",
        version: 1,
        requests: &[
        ],
        events: &[
            Message { name: "done", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "wl_compositor",
        version: 7,
        requests: &[
            Message { name: "create_surface", sig: "n:wl_surface", since: 1 },
            Message { name: "create_region", sig: "n:wl_region", since: 1 },
            Message { name: "release", sig: "", since: 7 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shm_pool",
        version: 3,
        requests: &[
            Message { name: "create_buffer", sig: "n:wl_buffer i i i i u", since: 1 },
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "resize", sig: "i", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shm",
        version: 3,
        requests: &[
            Message { name: "create_pool", sig: "n:wl_shm_pool h i", since: 1 },
            Message { name: "release", sig: "", since: 2 },
        ],
        events: &[
            Message { name: "format", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "wl_buffer",
        version: 1,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
        ],
        events: &[
            Message { name: "release", sig: "", since: 1 },
        ],
    },
    Interface {
        name: "wl_data_offer",
        version: 4,
        requests: &[
            Message { name: "accept", sig: "u ?s", since: 1 },
            Message { name: "receive", sig: "s h", since: 1 },
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "finish", sig: "", since: 3 },
            Message { name: "set_actions", sig: "u u", since: 3 },
        ],
        events: &[
            Message { name: "offer", sig: "s", since: 1 },
            Message { name: "source_actions", sig: "u", since: 3 },
            Message { name: "action", sig: "u", since: 3 },
        ],
    },
    Interface {
        name: "wl_data_source",
        version: 4,
        requests: &[
            Message { name: "offer", sig: "s", since: 1 },
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "set_actions", sig: "u", since: 3 },
        ],
        events: &[
            Message { name: "target", sig: "?s", since: 1 },
            Message { name: "send", sig: "s h", since: 1 },
            Message { name: "cancelled", sig: "", since: 1 },
            Message { name: "dnd_drop_performed", sig: "", since: 3 },
            Message { name: "dnd_finished", sig: "", since: 3 },
            Message { name: "action", sig: "u", since: 3 },
        ],
    },
    Interface {
        name: "wl_data_device",
        version: 4,
        requests: &[
            Message { name: "start_drag", sig: "?o o ?o u", since: 1 },
            Message { name: "set_selection", sig: "?o u", since: 1 },
            Message { name: "release", sig: "", since: 2 },
        ],
        events: &[
            Message { name: "data_offer", sig: "n:wl_data_offer", since: 1 },
            Message { name: "enter", sig: "u o f f ?o", since: 1 },
            Message { name: "leave", sig: "", since: 1 },
            Message { name: "motion", sig: "u f f", since: 1 },
            Message { name: "drop", sig: "", since: 1 },
            Message { name: "selection", sig: "?o", since: 1 },
        ],
    },
    Interface {
        name: "wl_data_device_manager",
        version: 4,
        requests: &[
            Message { name: "create_data_source", sig: "n:wl_data_source", since: 1 },
            Message { name: "get_data_device", sig: "n:wl_data_device o", since: 1 },
            Message { name: "release", sig: "", since: 4 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shell",
        version: 1,
        requests: &[
            Message { name: "get_shell_surface", sig: "n:wl_shell_surface o", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_shell_surface",
        version: 1,
        requests: &[
            Message { name: "pong", sig: "u", since: 1 },
            Message { name: "move", sig: "o u", since: 1 },
            Message { name: "resize", sig: "o u u", since: 1 },
            Message { name: "set_toplevel", sig: "", since: 1 },
            Message { name: "set_transient", sig: "o i i u", since: 1 },
            Message { name: "set_fullscreen", sig: "u u ?o", since: 1 },
            Message { name: "set_popup", sig: "o u o i i u", since: 1 },
            Message { name: "set_maximized", sig: "?o", since: 1 },
            Message { name: "set_title", sig: "s", since: 1 },
            Message { name: "set_class", sig: "s", since: 1 },
        ],
        events: &[
            Message { name: "ping", sig: "u", since: 1 },
            Message { name: "configure", sig: "u i i", since: 1 },
            Message { name: "popup_done", sig: "", since: 1 },
        ],
    },
    Interface {
        name: "wl_surface",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "attach", sig: "?o i i", since: 1 },
            Message { name: "damage", sig: "i i i i", since: 1 },
            Message { name: "frame", sig: "n:wl_callback", since: 1 },
            Message { name: "set_opaque_region", sig: "?o", since: 1 },
            Message { name: "set_input_region", sig: "?o", since: 1 },
            Message { name: "commit", sig: "", since: 1 },
            Message { name: "set_buffer_transform", sig: "i", since: 2 },
            Message { name: "set_buffer_scale", sig: "i", since: 3 },
            Message { name: "damage_buffer", sig: "i i i i", since: 4 },
            Message { name: "offset", sig: "i i", since: 5 },
            Message { name: "get_release", sig: "n:wl_callback", since: 7 },
        ],
        events: &[
            Message { name: "enter", sig: "o", since: 1 },
            Message { name: "leave", sig: "o", since: 1 },
            Message { name: "preferred_buffer_scale", sig: "i", since: 6 },
            Message { name: "preferred_buffer_transform", sig: "u", since: 6 },
        ],
    },
    Interface {
        name: "wl_seat",
        version: 11,
        requests: &[
            Message { name: "get_pointer", sig: "n:wl_pointer", since: 1 },
            Message { name: "get_keyboard", sig: "n:wl_keyboard", since: 1 },
            Message { name: "get_touch", sig: "n:wl_touch", since: 1 },
            Message { name: "release", sig: "", since: 5 },
        ],
        events: &[
            Message { name: "capabilities", sig: "u", since: 1 },
            Message { name: "name", sig: "s", since: 2 },
        ],
    },
    Interface {
        name: "wl_pointer",
        version: 11,
        requests: &[
            Message { name: "set_cursor", sig: "u ?o i i", since: 1 },
            Message { name: "release", sig: "", since: 3 },
        ],
        events: &[
            Message { name: "enter", sig: "u o f f", since: 1 },
            Message { name: "leave", sig: "u o", since: 1 },
            Message { name: "motion", sig: "u f f", since: 1 },
            Message { name: "button", sig: "u u u u", since: 1 },
            Message { name: "axis", sig: "u u f", since: 1 },
            Message { name: "frame", sig: "", since: 5 },
            Message { name: "axis_source", sig: "u", since: 5 },
            Message { name: "axis_stop", sig: "u u", since: 5 },
            Message { name: "axis_discrete", sig: "u i", since: 5 },
            Message { name: "axis_value120", sig: "u i", since: 8 },
            Message { name: "axis_relative_direction", sig: "u u", since: 9 },
            Message { name: "warp", sig: "f f", since: 11 },
        ],
    },
    Interface {
        name: "wl_keyboard",
        version: 11,
        requests: &[
            Message { name: "release", sig: "", since: 3 },
        ],
        events: &[
            Message { name: "keymap", sig: "u h u", since: 1 },
            Message { name: "enter", sig: "u o a", since: 1 },
            Message { name: "leave", sig: "u o", since: 1 },
            Message { name: "key", sig: "u u u u", since: 1 },
            Message { name: "modifiers", sig: "u u u u u", since: 1 },
            Message { name: "repeat_info", sig: "i i", since: 4 },
        ],
    },
    Interface {
        name: "wl_touch",
        version: 11,
        requests: &[
            Message { name: "release", sig: "", since: 3 },
        ],
        events: &[
            Message { name: "down", sig: "u u o i f f", since: 1 },
            Message { name: "up", sig: "u u i", since: 1 },
            Message { name: "motion", sig: "u i f f", since: 1 },
            Message { name: "frame", sig: "", since: 1 },
            Message { name: "cancel", sig: "", since: 1 },
            Message { name: "shape", sig: "i f f", since: 6 },
            Message { name: "orientation", sig: "i f", since: 6 },
        ],
    },
    Interface {
        name: "wl_output",
        version: 4,
        requests: &[
            Message { name: "release", sig: "", since: 3 },
        ],
        events: &[
            Message { name: "geometry", sig: "i i i i i s s i", since: 1 },
            Message { name: "mode", sig: "u i i i", since: 1 },
            Message { name: "done", sig: "", since: 2 },
            Message { name: "scale", sig: "i", since: 2 },
            Message { name: "name", sig: "s", since: 4 },
            Message { name: "description", sig: "s", since: 4 },
        ],
    },
    Interface {
        name: "wl_region",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "add", sig: "i i i i", since: 1 },
            Message { name: "subtract", sig: "i i i i", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_subcompositor",
        version: 1,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "get_subsurface", sig: "n:wl_subsurface o o", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_subsurface",
        version: 1,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "set_position", sig: "i i", since: 1 },
            Message { name: "place_above", sig: "o", since: 1 },
            Message { name: "place_below", sig: "o", since: 1 },
            Message { name: "set_sync", sig: "", since: 1 },
            Message { name: "set_desync", sig: "", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wl_fixes",
        version: 2,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "destroy_registry", sig: "o", since: 1 },
            Message { name: "ack_global_remove", sig: "o u", since: 2 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "xdg_wm_base",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "create_positioner", sig: "n:xdg_positioner", since: 1 },
            Message { name: "get_xdg_surface", sig: "n:xdg_surface o", since: 1 },
            Message { name: "pong", sig: "u", since: 1 },
        ],
        events: &[
            Message { name: "ping", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "xdg_positioner",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "set_size", sig: "i i", since: 1 },
            Message { name: "set_anchor_rect", sig: "i i i i", since: 1 },
            Message { name: "set_anchor", sig: "u", since: 1 },
            Message { name: "set_gravity", sig: "u", since: 1 },
            Message { name: "set_constraint_adjustment", sig: "u", since: 1 },
            Message { name: "set_offset", sig: "i i", since: 1 },
            Message { name: "set_reactive", sig: "", since: 3 },
            Message { name: "set_parent_size", sig: "i i", since: 3 },
            Message { name: "set_parent_configure", sig: "u", since: 3 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "xdg_surface",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "get_toplevel", sig: "n:xdg_toplevel", since: 1 },
            Message { name: "get_popup", sig: "n:xdg_popup ?o o", since: 1 },
            Message { name: "set_window_geometry", sig: "i i i i", since: 1 },
            Message { name: "ack_configure", sig: "u", since: 1 },
        ],
        events: &[
            Message { name: "configure", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "xdg_toplevel",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "set_parent", sig: "?o", since: 1 },
            Message { name: "set_title", sig: "s", since: 1 },
            Message { name: "set_app_id", sig: "s", since: 1 },
            Message { name: "show_window_menu", sig: "o u i i", since: 1 },
            Message { name: "move", sig: "o u", since: 1 },
            Message { name: "resize", sig: "o u u", since: 1 },
            Message { name: "set_max_size", sig: "i i", since: 1 },
            Message { name: "set_min_size", sig: "i i", since: 1 },
            Message { name: "set_maximized", sig: "", since: 1 },
            Message { name: "unset_maximized", sig: "", since: 1 },
            Message { name: "set_fullscreen", sig: "?o", since: 1 },
            Message { name: "unset_fullscreen", sig: "", since: 1 },
            Message { name: "set_minimized", sig: "", since: 1 },
        ],
        events: &[
            Message { name: "configure", sig: "i i a", since: 1 },
            Message { name: "close", sig: "", since: 1 },
            Message { name: "configure_bounds", sig: "i i", since: 4 },
            Message { name: "wm_capabilities", sig: "a", since: 5 },
        ],
    },
    Interface {
        name: "xdg_popup",
        version: 7,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "grab", sig: "o u", since: 1 },
            Message { name: "reposition", sig: "o u", since: 3 },
        ],
        events: &[
            Message { name: "configure", sig: "i i i i", since: 1 },
            Message { name: "popup_done", sig: "", since: 1 },
            Message { name: "repositioned", sig: "u", since: 3 },
        ],
    },
    Interface {
        name: "zxdg_decoration_manager_v1",
        version: 2,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "get_toplevel_decoration", sig: "n:zxdg_toplevel_decoration_v1 o", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "zxdg_toplevel_decoration_v1",
        version: 2,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "set_mode", sig: "u", since: 1 },
            Message { name: "unset_mode", sig: "", since: 1 },
        ],
        events: &[
            Message { name: "configure", sig: "u", since: 1 },
        ],
    },
    Interface {
        name: "wp_viewporter",
        version: 1,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "get_viewport", sig: "n:wp_viewport o", since: 1 },
        ],
        events: &[
        ],
    },
    Interface {
        name: "wp_viewport",
        version: 1,
        requests: &[
            Message { name: "destroy", sig: "", since: 1 },
            Message { name: "set_source", sig: "f f f f", since: 1 },
            Message { name: "set_destination", sig: "i i", since: 1 },
        ],
        events: &[
        ],
    },
];
