#!/usr/bin/env bash
# Tests for the servers the net zone's resolver forwards to
# (tools/net/netzone-init.sh, sync_upstream): a lease that comes late, another
# network's servers, a lease that lapsed and a file that cannot be written;
# and for how start_dns runs it. Offline, under each POSIX shell here.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT="${ROOT}/tools/net/netzone-init.sh"

PASS=0; FAIL=0
green() { printf '  PASS  %s\n' "$1"; PASS=$((PASS + 1)); }
red()   { printf '  FAIL  %s\n' "$1"; FAIL=$((FAIL + 1)); [[ $# -gt 1 ]] && printf '        %s\n' "$2"; }
same()  { if [[ "$2" == "$3" ]]; then green "$1"; else red "$1" "got '$(tr '\n' '|' <<<"$2")', want '$(tr '\n' '|' <<<"$3")'"; fi; }
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT

sed -n '/^sync_upstream() {/,/^}/p' "$SCRIPT" > "$T/functions.sh"
grep -q '^sync_upstream() {' "$T/functions.sh" \
    || { echo "could not find sync_upstream in ${SCRIPT#"$ROOT"/} (did its first line move?)"; exit 1; }
# The loop's own use of it: a resolver that is running is given the file, and
# no signal, which the zone's root cannot send its nobody.
grep -qE '^    elif \[ -n "\$DNSPID" \] && sync_upstream; then$' "$SCRIPT" && ! grep -q 'kill -HUP "\$DNSPID"' "$SCRIPT" \
    && green "the loop writes the servers for a running resolver, and sends it no signal" \
    || red "the loop no longer writes the servers on a change, or signals a resolver it cannot"
start="$(sed -n '/^start_dns() {/,/^}/p' "$SCRIPT" | grep -v '^ *#')"
# --no-poll would leave the file unread, and --no-daemon keeps dnsmasq root.
grep -q -- '--resolv-file="\$UPSTREAM" ' <<<"$start" && grep -q -- '--user=nobody' <<<"$start" \
    && ! grep -qE -- '--no-poll|--no-daemon' <<<"$start" \
    && green "dnsmasq runs as nobody and reads the file sync_upstream writes when it changes" \
    || red "dnsmasq is not started as nobody on the file sync_upstream writes"
# Shared by every zone: what it kept or counted would tell one zone what another looked up.
grep -qE -- '--cache-size=0( |$)' <<<"$start" && grep -q -- '--no-ident' <<<"$start" && ! grep -q -- '--use-stale-cache' <<<"$start" \
    && green "dnsmasq keeps no cache and no CHAOS records" \
    || red "dnsmasq keeps a cache, or answers CHAOS queries with its counters"

# step WHAT: one pass, as the loop makes it; prints its status and the file.
# umask 077: the file must still be one dnsmasq's nobody can read.
cat > "$T/harness.sh" <<EOF
umask 077
. "$T/functions.sh"
RESOLV="$T/resolv.conf"; UPSTREAM="\${UPSTREAM_AT:-$T/run/uplink-resolv.conf}"
sync_upstream; echo "rc=\$? \$(cat "\$UPSTREAM" 2>/dev/null | tr '\n' ',')"
EOF

for sh in sh bash dash; do
    command -v "$sh" >/dev/null 2>&1 || continue
    step() { "$sh" "$T/harness.sh" 2>&1; }
    rm -rf "$T/run" "$T/resolv.conf"; mkdir -p "$T/run"
    echo "-- ${sh}"
    same "no lease yet: nothing is written" "$(step)" "rc=1 "
    # As start_dns leaves it when nothing is known.
    echo "nameserver 10.0.2.3" > "$T/run/uplink-resolv.conf"
    printf 'search lan\n' > "$T/resolv.conf"
    same "a resolv.conf that names no server leaves the file as it is" "$(step)" "rc=1 nameserver 10.0.2.3,"
    printf '# Generated by dhcpcd from eth0.dhcp\ndomain lan\nnameserver 192.168.1.1\nnameserver fd00::1\noptions edns0\n' > "$T/resolv.conf"
    same "a lease that came late: its servers, IPv4 and IPv6, and nothing else of the file" "$(step)" "rc=0 nameserver 192.168.1.1,nameserver fd00::1,"
    same "the file is readable by all" "$(stat -c %a "$T/run/uplink-resolv.conf")" "644"
    same "the same servers again: no change, so no reload" "$(step)" "rc=1 nameserver 192.168.1.1,nameserver fd00::1,"
    [[ ! -e "$T/run/uplink-resolv.conf.new" ]] && green "the file is replaced whole: no temporary is left" || red "a temporary is left beside the file"
    printf 'nameserver 10.77.0.1\n' > "$T/resolv.conf"
    same "another network: its servers replace the last one's" "$(step)" "rc=0 nameserver 10.77.0.1,"
    : > "$T/resolv.conf"
    same "the lease lapsed: the last servers stay" "$(step)" "rc=1 nameserver 10.77.0.1,"
    rm -f "$T/resolv.conf"
    same "no resolv.conf at all: the last servers stay" "$(step)" "rc=1 nameserver 10.77.0.1,"
    printf 'nameserver 192.168.1.1\n' > "$T/resolv.conf"
    # Whatever the shell's status for the failed write, it is not a change.
    out="$(UPSTREAM_AT="$T/absent/uplink-resolv.conf" step | tail -n 1)"
    [[ "$out" =~ ^rc=[1-9][0-9]*\ $ ]] && green "a file that cannot be written is no change, and is tried at the next pass" \
        || red "a file that cannot be written" "got '${out}'"
done

echo
echo "${PASS} passed, ${FAIL} failed"
[[ "$FAIL" -eq 0 ]]
