#!/usr/bin/env python3
"""zone-colours.h from the zone files: one source for the colour of a zone.

The compositor (dwl, through build/desktop/dwl-config.h) draws a window's
border in its zone's colour, and kryptikd reads the same colour from the
zone's `[ui] border_color`. Two copies of that table drift; this generates
the compositor's copy from the zone files and `--check` refuses a stale
one, so the build (stage 04, s_dwl) and the test suite both catch a zone
whose border on screen is not the border in its definition.

    gen-zone-colours.py ZONES_DIR                 write the header to stdout
    gen-zone-colours.py --check HEADER ZONES_DIR  exit 1 if HEADER differs

The focused variant is derived, not configured: the same hue lifted 40%
towards white, so focus changes brightness and never identity.
"""
import os
import sys


def parse_flat_toml(text):
    """The subset kryptikd's own parser accepts: [section] and key = value,
    where a string value is double-quoted. A `#` inside the quotes is data
    (every colour starts with one); outside them it starts a comment."""
    out = {}
    section = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("["):
            section = line[1:line.index("]")].strip()
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        v = v.strip()
        if v.startswith('"'):
            end = v.find('"', 1)
            if end < 0:
                raise SystemExit(f"unterminated string for {k}")
            v = v[1:end]
        else:
            v = v.split("#", 1)[0].strip()
        out[f"{section}.{k}" if section else k] = v
    return out


def lift(hex6, amount=0.40):
    r, g, b = (int(hex6[i:i + 2], 16) for i in (0, 2, 4))
    f = lambda c: int(round(c + (255 - c) * amount))
    return "%02x%02x%02x" % (f(r), f(g), f(b))


def render(zones_dir):
    rows = []
    for name in sorted(os.listdir(zones_dir)):
        if not name.endswith(".toml"):
            continue
        with open(os.path.join(zones_dir, name), encoding="utf-8") as f:
            kv = parse_flat_toml(f.read())
        zone = kv.get("zone.name") or name[:-5]
        colour = kv.get("ui.border_color")
        if not colour:
            continue
        if len(colour) != 7 or colour[0] != "#" or any(c not in "0123456789abcdefABCDEF" for c in colour[1:]):
            raise SystemExit(f"{name}: ui.border_color {colour!r} is not #rrggbb")
        hex6 = colour[1:].lower()
        rows.append((zone, hex6, lift(hex6)))
    if not rows:
        raise SystemExit(f"no zone with a border_color under {zones_dir}")
    width = max(len(z) for z, _, _ in rows) + 3
    lines = [
        "/* Kryptik zone colours: the one table both the compositor (dwl config.h)",
        " * and the trusted chrome draw from, so a window border and the bar agree.",
        " *",
        " * GENERATED by tools/desktop/gen-zone-colours.py from compartments/zones/",
        " * ([ui] border_color of each zone); do not edit. The focused colour is the",
        " * border lifted 40% towards white.",
        " *",
        " * X(zone, border, focused-border) - 0xRRGGBBAA. A window whose app_id has",
        " * no `kryptik.<zone>.` prefix did not come through a zone proxy and is",
        " * drawn with UNZONED; a prefix naming a zone not listed here gets UNKNOWN,",
        " * which is deliberately the loudest colour on the table.",
        " */",
        "#ifndef KRYPTIK_ZONE_COLOURS_H",
        "#define KRYPTIK_ZONE_COLOURS_H",
        "",
        "#define KRYPTIK_ZONE_COLOURS(X) \\",
    ]
    for i, (zone, border, focus) in enumerate(rows):
        tail = " \\" if i + 1 < len(rows) else ""
        lines.append("\tX(%-*s 0x%sff, 0x%sff)%s" % (width, '"%s",' % zone, border, focus, tail))
    lines += [
        "",
        "#define KRYPTIK_UNZONED_BORDER  0xd8d8d8ff",
        "#define KRYPTIK_UNZONED_FOCUS   0xffffffff",
        "#define KRYPTIK_UNKNOWN_BORDER  0xff00c8ff",
        "#define KRYPTIK_UNKNOWN_FOCUS   0xff66e0ff",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    if len(argv) == 1:
        # Bytes, so a Windows Python does not turn the header into CRLF.
        sys.stdout.buffer.write(render(argv[0]).encode("utf-8"))
        return 0
    if len(argv) == 3 and argv[0] == "--check":
        want = render(argv[2])
        try:
            with open(argv[1], encoding="utf-8") as f:
                have = f.read()
        except OSError as e:
            sys.stderr.write(f"gen-zone-colours: {e}\n")
            return 1
        if have != want:
            sys.stderr.write(
                f"gen-zone-colours: {argv[1]} does not match the zone files in {argv[2]}.\n"
                f"Regenerate it:  tools/desktop/gen-zone-colours.py {argv[2]} > {argv[1]}\n")
            return 1
        print(f"gen-zone-colours: {argv[1]} matches {argv[2]}")
        return 0
    sys.stderr.write(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
