#!/usr/bin/env python3
"""Generate dwl's zone-colours.h from the zones' [ui] border_color.

    gen-zone-colours.py ZONES_DIR                 write the header to stdout
    gen-zone-colours.py --check HEADER ZONES_DIR  exit 1 if HEADER differs
"""
import os
import sys

# zoneid's COMPOSITOR_COLOURS; its header test keeps the two equal.
FIXED =(("UNZONED", "d8d8d8"), ("UNKNOWN", "a2c9ff"), ("URGENT", "ffd000"))


def parse_flat_toml(text):
    """Parse [section] / key = value; a quoted `#` is data, a repeated key an error."""
    out = {}
    section = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("["):
            section = line[1:line.index("]")].strip()
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        v = v.strip()
        if v.startswith('"'):
            end = v.find('"', 1)
            if end < 0:
                raise SystemExit(f"unterminated string for {k}")
            v = v[1:end]
        else:
            v = v.split("#", 1)[0].strip()
        key = f"{section}.{k}" if section else k
        if key in out:
            raise SystemExit(f"{key} is given twice")
        out[key] = v
    return out


def render(zones_dir):
    rows = []
    for name in sorted(os.listdir(zones_dir)):
        if not name.endswith(".toml"):
            continue
        with open(os.path.join(zones_dir, name), encoding="utf-8") as f:
            kv = parse_flat_toml(f.read())
        zone = kv.get("zone.name") or name[:-5]
        colour = kv.get("ui.border_color")
        if not colour:
            continue
        if len(colour) != 7 or colour[0] != "#" or any(c not in "0123456789abcdefABCDEF" for c in colour[1:]):
            raise SystemExit(f"{name}: ui.border_color {colour!r} is not #rrggbb")
        rows.append((zone, colour[1:].lower()))
    if not rows:
        raise SystemExit(f"no zone with a border_color under {zones_dir}")
    width = max(len(z) for z, _ in rows) + 3
    lines = [
        "/* Kryptik zone colours: the border colours dwl draws, and nothing else.",
        " *",
        " * GENERATED by tools/desktop/gen-zone-colours.py from compartments/zones/",
        " * ([ui] border_color of each zone); do not edit.",
        " *",
        " * X(zone, border) - 0xRRGGBBAA. A window whose app_id has no",
        " * `kryptik.<zone>.` prefix did not come through a zone proxy and is drawn",
        " * UNZONED; a prefix naming a zone not listed here is drawn UNKNOWN.",
        " */",
        "#ifndef KRYPTIK_ZONE_COLOURS_H",
        "#define KRYPTIK_ZONE_COLOURS_H",
        "",
        "#define KRYPTIK_ZONE_COLOURS(X) \\",
    ]
    for i, (zone, border) in enumerate(rows):
        tail = " \\" if i + 1 < len(rows) else ""
        lines.append("\tX(%-*s 0x%sff)%s" % (width, '"%s",' % zone, border, tail))
    lines.append("")
    lines += ["#define %-24s0x%sff" % ("KRYPTIK_%s_BORDER" % name, hex6) for name, hex6 in FIXED]
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def main(argv):
    if len(argv) == 1:
        # Bytes, so a Windows Python does not turn the header into CRLF.
        sys.stdout.buffer.write(render(argv[0]).encode("utf-8"))
        return 0
    if len(argv) == 3 and argv[0] == "--check":
        want = render(argv[2])
        try:
            with open(argv[1], encoding="utf-8") as f:
                have = f.read()
        except OSError as e:
            sys.stderr.write(f"gen-zone-colours: {e}\n")
            return 1
        if have != want:
            sys.stderr.write(
                f"gen-zone-colours: {argv[1]} does not match the zone files in {argv[2]}.\n"
                f"Regenerate it:  tools/desktop/gen-zone-colours.py {argv[2]} > {argv[1]}\n")
            return 1
        print(f"gen-zone-colours: {argv[1]} matches {argv[2]}")
        return 0
    sys.stderr.write(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
