#!/usr/bin/env python3
"""Generate compositor/wlproxy/src/protocol_tables.rs from Wayland protocol XML.

usage: tools/desktop/gen-wl-protocol.py OUT.rs wayland.xml xdg-shell.xml ...
"""
import hashlib, sys, xml.etree.ElementTree as ET

SIMPLE = {"int": "Arg::Int", "uint": "Arg::Uint", "fixed": "Arg::Fixed", "array": "Arg::Array", "fd": "Arg::Fd"}

def args_of(msg):
    """The message's arguments as Rust, in wire order, and its fd count; an unknown type raises."""
    args, fds = [], 0
    for a in msg.findall("arg"):
        t = a.get("type"); nullable = "true" if a.get("allow-null") == "true" else "false"
        if t == "new_id":
            iface = a.get("interface")
            # No interface (wl_registry.bind): the client names it on the wire, before the id.
            args.append(f'Arg::NewId {{ iface: Some("{iface}") }}' if iface else "Arg::NewId { iface: None }")
        elif t in ("string", "object"):
            args.append(f"Arg::{t.capitalize()} {{ nullable: {nullable} }}")
        else:
            args.append(SIMPLE[t])
            fds += t == "fd"
    return "&[" + ", ".join(args) + "]", fds

def row(m):
    args, fds = args_of(m)
    return f"            Message {{ name: \"{m.get('name')}\", args: {args}, fds: {fds}, since: {int(m.get('since', '1'))} }},\n"

def main():
    out = sys.argv[1]; files = sys.argv[2:]
    ifaces = []
    sources = []
    for f in files:
        data = open(f, "rb").read()
        sources.append((f.split("/")[-1], hashlib.sha256(data).hexdigest()))
        root = ET.fromstring(data)
        for it in root.findall("interface"):
            name = it.get("name"); version = int(it.get("version"))
            reqs = [row(m) for m in it.findall("request")]
            evts = [row(m) for m in it.findall("event")]
            ifaces.append((name, version, reqs, evts))
    with open(out, "w", newline="\n") as w:
        w.write("// GENERATED by tools/desktop/gen-wl-protocol.py - do not edit.\n")
        w.write("// Sources:\n")
        for n, h in sources:
            w.write(f"//   {n}  sha256 {h}\n")
        w.write("//\n// Each message's arguments in wire order, and how many are descriptors. A\n")
        w.write("// new_id with no interface is wl_registry.bind's, which the client names.\n\n")
        w.write("use super::protocol::{Arg, Interface, Message};\n\n")
        w.write("pub static INTERFACES: &[Interface] = &[\n")
        for name, version, reqs, evts in ifaces:
            w.write(f"    Interface {{\n        name: \"{name}\",\n        version: {version},\n")
            w.write("        requests: &[\n")
            w.writelines(reqs)
            w.write("        ],\n        events: &[\n")
            w.writelines(evts)
            w.write("        ],\n    },\n")
        w.write("];\n")
    print(f"wrote {out}: {len(ifaces)} interfaces from {len(files)} files")

if __name__ == "__main__":
    main()
