#!/usr/bin/env python3
"""Generate compositor/wlproxy/src/protocol_tables.rs from Wayland protocol XML.

    tools/desktop/gen-wl-protocol.py OUT.rs wayland.xml xdg-shell.xml ...

The proxy needs, for every interface it lets through, the exact signature of
every request and event: which arguments are new_id (and of which interface),
which are file descriptors (they occupy no bytes on the wire), and the
version each interface was defined at. Getting a single fd count wrong
desynchronises the descriptor queue from the byte stream, so this is
generated from upstream's XML rather than typed.

Signature letters follow libwayland: i u f s o n a h, with '?' before a
nullable o/s, and n carries its interface name after a colon in the table.
"""
import hashlib, sys, xml.etree.ElementTree as ET

def sig_of(msg):
    parts = []
    for a in msg.findall("arg"):
        t = a.get("type"); nullable = a.get("allow-null") == "true"
        c = {"int": "i", "uint": "u", "fixed": "f", "string": "s", "object": "o",
             "new_id": "n", "array": "a", "fd": "h"}[t]
        if t == "new_id":
            iface = a.get("interface")
            # wl_registry.bind's new_id has no interface: the client names it
            # (string, uint version) before the id on the wire.
            parts.append("n:" + (iface or "*"))
        else:
            parts.append(("?" if nullable else "") + c)
    return " ".join(parts)

def main():
    out = sys.argv[1]; files = sys.argv[2:]
    ifaces = []
    sources = []
    for f in files:
        data = open(f, "rb").read()
        sources.append((f.split("/")[-1], hashlib.sha256(data).hexdigest()))
        root = ET.fromstring(data)
        for it in root.findall("interface"):
            name = it.get("name"); version = int(it.get("version"))
            reqs = [(m.get("name"), sig_of(m), int(m.get("since", "1"))) for m in it.findall("request")]
            evts = [(m.get("name"), sig_of(m), int(m.get("since", "1"))) for m in it.findall("event")]
            ifaces.append((name, version, reqs, evts))
    with open(out, "w", newline="\n") as w:
        w.write("// GENERATED by tools/desktop/gen-wl-protocol.py - do not edit.\n")
        w.write("// Sources:\n")
        for n, h in sources:
            w.write(f"//   {n}  sha256 {h}\n")
        w.write("//\n// Signature letters: i u f s o n a h; '?' marks a nullable o/s; n:iface names\n")
        w.write("// the new object's interface, n:* means the client names it (wl_registry.bind).\n\n")
        w.write("use super::protocol::{Interface, Message};\n\n")
        w.write("pub static INTERFACES: &[Interface] = &[\n")
        for name, version, reqs, evts in ifaces:
            w.write(f"    Interface {{\n        name: \"{name}\",\n        version: {version},\n")
            w.write("        requests: &[\n")
            for n, s, since in reqs:
                w.write(f"            Message {{ name: \"{n}\", sig: \"{s}\", since: {since} }},\n")
            w.write("        ],\n        events: &[\n")
            for n, s, since in evts:
                w.write(f"            Message {{ name: \"{n}\", sig: \"{s}\", since: {since} }},\n")
            w.write("        ],\n    },\n")
        w.write("];\n")
    print(f"wrote {out}: {len(ifaces)} interfaces from {len(files)} files")

if __name__ == "__main__":
    main()
